language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get install tree
  
install:
  - pip install -e .
  - pip install -r requirements-dev.txt

script:
  - make test
